# Generated by Django 3.2.20 on 2023-07-20 11:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('about', models.TextField()),
                ('event_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('link', models.URLField(blank=True)),
                ('event_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.CharField(choices=[('jamtland', 'Jämtland'), ('ostersund', 'Östersund'), ('krokom', 'Krokom'), ('berg', 'Berg'), ('are', 'Åre'), ('bracke', 'Bräcke'), ('harjedalen', 'Härjedalen'), ('ragunda', 'Ragunda'), ('stromsund', 'Strömsund')], default='jamtland', max_length=100)),
                ('locale', models.CharField(max_length=100)),
                ('event_type', models.IntegerField(choices=[(0, 'Music'), (1, 'Art'), (2, 'Other')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Done'), (3, 'Cancelled')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
