# Generated by Django 3.2.20 on 2023-07-20 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_post_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
