# Generated by Django 3.2.20 on 2023-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20230720_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='event_start',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
