# Generated by Django 3.2.20 on 2023-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20230720_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_status',
            field=models.CharField(choices=[('initial', 'Initial'), ('passed', 'Passed'), ('cancelled', 'Cancelled')], default='initial', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
