# Generated by Django 3.2.20 on 2023-07-22 13:28

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20230722_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=200, populate_from=('title', 'even_start'), unique=True),
        ),
    ]
