# Generated by Django 3.2.20 on 2023-07-22 13:30

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=200, populate_from=['title', 'event_start'], unique=True),
        ),
    ]
